const CAKES = [
  {
    id: 1,
    name: 'Bánh Flan',
    region: 'Nam',
    category: 'Bánh tráng miệng',
    origin: 'TP. Hồ Chí Minh',
    description: 'Bánh flan mềm mịn với lớp caramel thơm ngậy, tan chảy ngay khi vào miệng.',
    detail: 'Bánh flan (crème caramel) du nhập vào Việt Nam qua ảnh hưởng ẩm thực Pháp. Tại miền Nam, bánh được biến tấu thêm với cà phê đen, dừa hoặc matcha. Kết cấu mềm mượt, lớp caramel ngọt đắng phủ trên tạo màu vàng óng hấp dẫn. Thường được ăn lạnh trong ngày hè oi bức.',
    ingredients: ['Trứng gà', 'Sữa tươi', 'Đường', 'Caramel', 'Vani'],
    occasion: 'Hàng ngày, tráng miệng',
    rating: 4.8,
    gradient: 'linear-gradient(135deg, #f6d365 0%, #fda085 100%)',
    emoji: '🍮'
  },
  {
    id: 2,
    name: 'Bánh Bông Lan',
    region: 'Bắc',
    category: 'Bánh nướng',
    origin: 'Hà Nội',
    description: 'Bánh bông lan xốp nhẹ, vàng ruộm, thơm hấp dẫn — loại bánh nướng quen thuộc nhất.',
    detail: 'Bánh bông lan (sponge cake) phổ biến tại các tiệm bánh Việt Nam từ thập niên 1980. Với kỹ thuật đánh bông trứng tạo cấu trúc xốp đặc trưng, bánh có vị ngọt thanh, mềm mịn. Người Hà Nội thường dùng bánh bông lan kèm trà buổi sáng hoặc chiều tà.',
    ingredients: ['Bột mì', 'Trứng gà', 'Đường', 'Bơ', 'Bột nở', 'Vani'],
    occasion: 'Hàng ngày, buổi sáng - chiều',
    rating: 4.3,
    gradient: 'linear-gradient(135deg, #f9d423 0%, #ff4e50 100%)',
    emoji: '🎂'
  },
  {
    id: 3,
    name: 'Bánh Su Kem',
    region: 'Nam',
    category: 'Bánh tráng miệng',
    origin: 'TP. Hồ Chí Minh',
    description: 'Vỏ bánh giòn xốp, nhân kem vani béo ngậy — chiếc bánh Pháp được người Việt yêu thích.',
    detail: 'Bánh su kem (choux à la crème) được người Pháp mang đến Việt Nam từ thế kỷ XIX. Vỏ bánh từ bột choux phồng giòn, bên trong phun đầy kem vani hoặc kem tươi đánh bông. Tại Sài Gòn, nhiều tiệm biến tấu nhân với pandan, dâu tây, sô cô la.',
    ingredients: ['Bột mì', 'Bơ', 'Trứng gà', 'Sữa tươi', 'Kem tươi', 'Đường bột', 'Vani'],
    occasion: 'Tráng miệng, quà tặng',
    rating: 4.7,
    gradient: 'linear-gradient(135deg, #a18cd1 0%, #fbc2eb 100%)',
    emoji: '🧁'
  },
  {
    id: 4,
    name: 'Bánh Trung Thu',
    region: 'Bắc',
    category: 'Bánh nướng',
    origin: 'Hà Nội',
    description: 'Bánh trung thu nướng nhân thập cẩm hay đậu xanh — biểu tượng Tết Trung thu Việt Nam.',
    detail: 'Bánh trung thu là loại bánh truyền thống không thể thiếu trong dịp Tết Trung thu (rằm tháng 8 âm lịch). Bánh nướng có vỏ vàng óng, hoa văn nổi đẹp mắt; nhân phổ biến gồm thập cẩm, đậu xanh, hạt sen. Ngày nay còn có bánh dẻo với vỏ trắng mịn, nhân đa dạng.',
    ingredients: ['Bột mì', 'Nước đường', 'Dầu ăn', 'Đậu xanh', 'Hạt sen', 'Mứt', 'Trứng muối'],
    occasion: 'Tết Trung thu',
    rating: 4.9,
    gradient: 'linear-gradient(135deg, #f7971e 0%, #ffd200 100%)',
    emoji: '🥮'
  },
  {
    id: 5,
    name: 'Bánh Pía',
    region: 'Nam',
    category: 'Bánh nướng',
    origin: 'Sóc Trăng',
    description: 'Đặc sản Sóc Trăng với vỏ nhiều lớp giòn mỏng, nhân đậu xanh sầu riêng thơm nức.',
    detail: 'Bánh pía là đặc sản của người Hoa tại Sóc Trăng, có nguồn gốc từ bánh Suzhou (Trung Quốc). Vỏ bánh làm nhiều lớp bột mỏng xen lẫn mỡ, tạo độ giòn đặc trưng. Nhân truyền thống là đậu xanh sầu riêng kết hợp lòng đỏ trứng vịt muối, tạo hương vị béo bùi đậm đà.',
    ingredients: ['Bột mì', 'Mỡ heo', 'Đậu xanh', 'Sầu riêng', 'Trứng vịt muối', 'Đường'],
    occasion: 'Quà biếu, Tết',
    rating: 4.6,
    gradient: 'linear-gradient(135deg, #d4a76a 0%, #8b5e3c 100%)',
    emoji: '🥧'
  },
  {
    id: 6,
    name: 'Bánh Da Lợn',
    region: 'Nam',
    category: 'Bánh hấp',
    origin: 'TP. Hồ Chí Minh',
    description: 'Bánh nhiều lớp xanh - vàng xen kẽ, dai mềm, thơm lá dứa và đậu xanh béo ngọt.',
    detail: 'Bánh da lợn (bánh da heo) là loại bánh hấp truyền thống của người Hoa ở miền Nam. Bánh gồm nhiều lớp xen kẽ giữa màu xanh lá dứa và màu vàng đậu xanh, trong suốt như thạch. Kết cấu dai mềm, vị ngọt thanh với hương thơm đặc trưng của lá dứa và nước cốt dừa.',
    ingredients: ['Bột năng', 'Đậu xanh', 'Nước cốt dừa', 'Lá dứa', 'Đường', 'Muối'],
    occasion: 'Hàng ngày, cúng giỗ',
    rating: 4.4,
    gradient: 'linear-gradient(135deg, #56ab2f 0%, #a8e6cf 100%)',
    emoji: '🟩'
  },
  {
    id: 7,
    name: 'Bánh Chuối Hấp',
    region: 'Nam',
    category: 'Bánh hấp',
    origin: 'Đồng bằng sông Cửu Long',
    description: 'Bánh chuối dẻo thơm, ngọt béo nước cốt dừa — món quà vặt dân dã của miền Tây.',
    detail: 'Bánh chuối hấp gắn liền với vùng đồng bằng sông Cửu Long, nơi chuối trồng rất phong phú. Bánh từ chuối chín, bột năng, nước cốt dừa hấp chín. Mặt bánh có thêm lớp nước cốt dừa đặc cùng đậu phộng rang giòn, vừng trắng thơm bùi.',
    ingredients: ['Chuối chín', 'Bột năng', 'Nước cốt dừa', 'Đường', 'Muối', 'Đậu phộng', 'Vừng'],
    occasion: 'Hàng ngày, quà vặt',
    rating: 4.2,
    gradient: 'linear-gradient(135deg, #f7e062 0%, #f9a825 100%)',
    emoji: '🍌'
  },
  {
    id: 8,
    name: 'Bánh Rán',
    region: 'Bắc',
    category: 'Bánh chiên',
    origin: 'Hà Nội',
    description: 'Bánh rán vừng giòn rụm bên ngoài, nhân đậu xanh ngọt bùi — đặc sản phố cổ Hà Nội.',
    detail: 'Bánh rán là một trong những món bánh chiên dân gian lâu đời nhất của miền Bắc. Vỏ bánh từ bột nếp, bao quanh nhân đậu xanh ngọt, áo lớp vừng trắng dày rồi chiên ngập dầu đến vàng giòn. Bánh được bán dạo trên phố hoặc tại các chợ Hà Nội từ rất sớm.',
    ingredients: ['Bột nếp', 'Đậu xanh', 'Đường', 'Vừng trắng', 'Dầu ăn', 'Muối'],
    occasion: 'Hàng ngày, buổi sáng - chiều',
    rating: 4.5,
    gradient: 'linear-gradient(135deg, #c8a96e 0%, #f5deb3 100%)',
    emoji: '🍩'
  },
  {
    id: 9,
    name: 'Bánh Cam',
    region: 'Nam',
    category: 'Bánh chiên',
    origin: 'TP. Hồ Chí Minh',
    description: 'Bánh cam vàng tròn giòn rụm, nhân đậu xanh béo, lăn vừng — hương vị tuổi thơ Sài Gòn.',
    detail: 'Bánh cam là biến thể miền Nam của bánh rán miền Bắc, kích thước nhỏ hơn và vị ngọt đậm hơn. Vỏ bánh giòn xốp hơn do thêm bột mì bên cạnh bột nếp, lớp vừng áo bên ngoài vàng đều. Tên "bánh cam" từ màu vàng cam đẹp mắt sau khi chiên.',
    ingredients: ['Bột nếp', 'Bột mì', 'Đậu xanh', 'Đường', 'Vừng', 'Dầu ăn'],
    occasion: 'Quà vặt, hàng ngày',
    rating: 4.3,
    gradient: 'linear-gradient(135deg, #f7971e 0%, #ffd200 100%)',
    emoji: '🟠'
  },
  {
    id: 10,
    name: 'Bánh Tiêu',
    region: 'Nam',
    category: 'Bánh chiên',
    origin: 'TP. Hồ Chí Minh',
    description: 'Bánh tiêu xốp giòn, rỗng ruột, rắc vừng thơm — ăn nóng hổi cùng cháo trắng tuyệt vời.',
    detail: 'Bánh tiêu là loại bánh chiên phổ biến ở miền Nam, có nguồn gốc từ cộng đồng người Hoa. Bánh từ bột mì có men, khi chiên phồng to và rỗng bên trong, bên ngoài giòn rụm, rắc vừng thơm. Người Sài Gòn thường ăn bánh tiêu kèm cháo trắng vào buổi sáng.',
    ingredients: ['Bột mì', 'Men nở', 'Đường', 'Vừng', 'Dầu ăn', 'Muối'],
    occasion: 'Bữa sáng, quà vặt',
    rating: 4.4,
    gradient: 'linear-gradient(135deg, #e8c99a 0%, #c8a96e 100%)',
    emoji: '🫓'
  },
  {
    id: 11,
    name: 'Bánh Trôi',
    region: 'Bắc',
    category: 'Bánh dân gian',
    origin: 'Hà Nội',
    description: 'Bánh trôi trắng tròn nhân đường phèn — món bánh Tết Hàn thực không thể thiếu của miền Bắc.',
    detail: 'Bánh trôi là loại bánh truyền thống gắn liền với Tết Hàn thực (mùng 3 tháng 3 âm lịch). Bánh từ bột nếp trắng, nhân đường phèn, luộc chín nổi mặt nước. Bài thơ "Bánh trôi nước" của Hồ Xuân Hương đã làm loại bánh này trở thành biểu tượng văn hóa Việt.',
    ingredients: ['Bột nếp', 'Đường phèn', 'Vừng đen', 'Nước', 'Muối'],
    occasion: 'Tết Hàn thực, cúng giỗ',
    rating: 4.6,
    gradient: 'linear-gradient(135deg, #e0eafc 0%, #cfdef3 100%)',
    emoji: '⚪'
  },
  {
    id: 12,
    name: 'Bánh Cốm',
    region: 'Bắc',
    category: 'Bánh dân gian',
    origin: 'Hà Nội',
    description: 'Bánh cốm xanh ngọt dịu từ cốm Vòng, nhân đậu xanh mứt sen — đặc sản mùa thu Hà Nội.',
    detail: 'Bánh cốm là đặc sản nổi tiếng của Hà Nội, làm từ cốm Vòng — loại gạo nếp non xanh đặc trưng của làng Vòng, Cầu Giấy. Bánh màu xanh ngọc đẹp mắt, nhân đậu xanh nấu chín trộn mứt sen. Trong văn hóa Hà Nội, bánh cốm thường xuất hiện trong mâm quà cưới hỏi, đám giỗ mùa thu.',
    ingredients: ['Cốm Vòng', 'Đậu xanh', 'Mứt sen', 'Đường', 'Nước cốt dừa'],
    occasion: 'Cưới hỏi, Tết, mùa thu',
    rating: 4.7,
    gradient: 'linear-gradient(135deg, #56ab2f 0%, #a8e063 100%)',
    emoji: '🟢'
  },
  {
    id: 13,
    name: 'Bánh Xu Xê',
    region: 'Bắc',
    category: 'Bánh dân gian',
    origin: 'Hà Nội',
    description: 'Bánh xu xê trong suốt đẹp mắt, nhân đậu xanh dừa thơm — thường có mặt trong mâm cưới.',
    detail: 'Bánh xu xê (phu thê) là loại bánh truyền thống xuất hiện trong lễ cưới người Việt miền Bắc, tượng trưng cho sự gắn kết vợ chồng. Vỏ bánh từ bột năng trong suốt như thủy tinh, nhân đậu xanh dừa ngọt béo. Bánh thường được gói trong lá chuối xanh hoặc hộp giấy xinh xắn.',
    ingredients: ['Bột năng', 'Đậu xanh', 'Dừa nạo', 'Đường', 'Nước lá dứa', 'Hạt gấc'],
    occasion: 'Lễ cưới, hỏi',
    rating: 4.5,
    gradient: 'linear-gradient(135deg, #ffecd2 0%, #fcb69f 100%)',
    emoji: '💛'
  },
  {
    id: 14,
    name: 'Bánh Bèo',
    region: 'Trung',
    category: 'Bánh hấp',
    origin: 'Huế',
    description: 'Bánh bèo Huế trắng mịn, nhân tôm chấy mặn ngọt — ăn cùng nước mắm pha chua ngọt.',
    detail: 'Bánh bèo là đặc sản ẩm thực cung đình Huế, từng được phục vụ trong các bữa tiệc hoàng gia. Bánh từ bột gạo hấp trong chén nhỏ, mặt bánh phẳng như lá bèo trên ao. Nhân tôm chấy đỏ thơm, mỡ hành xanh, nước mắm pha chua ngọt tạo sự hài hòa tinh tế đặc trưng ẩm thực Huế.',
    ingredients: ['Bột gạo', 'Tôm khô', 'Mỡ hành', 'Nước mắm', 'Đường', 'Chanh', 'Ớt'],
    occasion: 'Hàng ngày, ăn vặt',
    rating: 4.5,
    gradient: 'linear-gradient(135deg, #fff9c4 0%, #f9a825 100%)',
    emoji: '🍚'
  },
  {
    id: 15,
    name: 'Bánh Khoai Mì Nướng',
    region: 'Nam',
    category: 'Bánh nướng',
    origin: 'Đồng bằng sông Cửu Long',
    description: 'Bánh khoai mì nướng vàng ruộm, thơm nước cốt dừa, dai dẻo — đặc sản dân dã miền Tây.',
    detail: 'Bánh khoai mì nướng là món bánh giản dị đặc trưng của vùng đồng bằng sông Cửu Long. Khoai mì bào nhỏ trộn nước cốt dừa, đường, trứng rồi đổ khuôn nướng đến vàng. Mặt bánh giòn, ruột dai dẻo, mùi thơm của nước cốt dừa nướng rất hấp dẫn.',
    ingredients: ['Khoai mì', 'Nước cốt dừa', 'Đường', 'Trứng gà', 'Muối', 'Vừng'],
    occasion: 'Quà vặt, hàng ngày',
    rating: 4.3,
    gradient: 'linear-gradient(135deg, #c8a96e 0%, #f5deb3 100%)',
    emoji: '🟤'
  },
  {
    id: 16,
    name: 'Bánh Kem Sinh Nhật',
    region: 'Bắc',
    category: 'Bánh kem',
    origin: 'Hà Nội',
    description: 'Bánh kem nhiều tầng phủ kem tươi, trang trí hoa quả — không thể thiếu trong ngày sinh nhật.',
    detail: 'Bánh kem sinh nhật du nhập vào Việt Nam từ những năm 1970-1980 và nhanh chóng trở thành biểu tượng ngày lễ sinh nhật. Bánh thường có 2-3 tầng bông lan mềm, xen kẽ kem tươi đánh bông, phủ ngoài bằng kem butter hoặc kem tươi rồi trang trí hoa quả, socola. Tiệm bánh kem đầu tiên tại Hà Nội là Brodard.',
    ingredients: ['Bột mì', 'Trứng', 'Đường', 'Kem tươi', 'Bơ', 'Hoa quả tươi', 'Socola'],
    occasion: 'Sinh nhật, kỷ niệm',
    rating: 4.9,
    gradient: 'linear-gradient(135deg, #ff9a9e 0%, #fecfef 100%)',
    emoji: '🎂'
  },
  {
    id: 17,
    name: 'Bánh Cupcake Matcha',
    region: 'Bắc',
    category: 'Bánh kem',
    origin: 'Hà Nội',
    description: 'Cupcake matcha phong cách Nhật — vị đắng thanh của trà xanh hòa quyện kem tươi ngọt.',
    detail: 'Bánh cupcake matcha là loại bánh phong cách Nhật Bản được các tiệm bánh Việt ưa chuộng những năm gần đây. Vỏ bánh bông lan xanh matcha thơm nhẹ, bên trên phủ kem tươi xoáy cao hoặc kem cream cheese vị matcha. Sự kết hợp thú vị giữa kỹ thuật làm bánh phương Tây và nguyên liệu châu Á.',
    ingredients: ['Bột mì', 'Bột matcha', 'Trứng', 'Đường', 'Bơ', 'Sữa tươi', 'Kem tươi'],
    occasion: 'Quà tặng, sinh nhật, hàng ngày',
    rating: 4.6,
    gradient: 'linear-gradient(135deg, #96c93d 0%, #00b09b 100%)',
    emoji: '🍵'
  },
  {
    id: 18,
    name: 'Bánh Tét Ngọt',
    region: 'Nam',
    category: 'Bánh dân gian',
    origin: 'Đồng bằng sông Cửu Long',
    description: 'Bánh tét nhân chuối hoặc đậu đen ngọt, gói lá chuối — món Tết không thể thiếu ở miền Nam.',
    detail: 'Bánh tét là phiên bản miền Nam của bánh chưng, hình trụ dài thay vì hình vuông. Bánh tét ngọt thường có nhân chuối sứ chín hoặc đậu đen ngọt. Gạo nếp gói cùng nhân trong lá chuối, luộc nhiều giờ cho đến khi chín dẻo. Người miền Nam ăn bánh tét trong 3 ngày Tết Nguyên đán.',
    ingredients: ['Gạo nếp', 'Chuối sứ', 'Đường', 'Nước cốt dừa', 'Lá chuối', 'Muối'],
    occasion: 'Tết Nguyên đán',
    rating: 4.7,
    gradient: 'linear-gradient(135deg, #2d6a4f 0%, #52b788 100%)',
    emoji: '🫘'
  },
  {
    id: 19,
    name: 'Bánh Mì Ngọt',
    region: 'Nam',
    category: 'Bánh nướng',
    origin: 'TP. Hồ Chí Minh',
    description: 'Bánh mì ngọt vỏ giòn ruột xốp, nhân kem bơ hoặc dừa béo — bữa sáng quốc dân Sài Gòn.',
    detail: 'Bánh mì ngọt là sản phẩm giao thoa giữa baguette Pháp và khẩu vị Việt Nam. Tại Sài Gòn, bánh mì ngọt nhỏ hơn baguette, vỏ mỏng giòn, ruột xốp mềm hơn. Nhân đa dạng gồm kem bơ, dừa nạo đường, pate, thịt nguội. Đây là bữa sáng phổ biến và rẻ tiền nhất tại Sài Gòn.',
    ingredients: ['Bột mì', 'Men nở', 'Đường', 'Bơ', 'Trứng', 'Sữa', 'Kem bơ'],
    occasion: 'Bữa sáng, hàng ngày',
    rating: 4.5,
    gradient: 'linear-gradient(135deg, #e8c99a 0%, #d4a76a 100%)',
    emoji: '🥖'
  },
  {
    id: 20,
    name: 'Bánh Dừa Nướng',
    region: 'Trung',
    category: 'Bánh nướng',
    origin: 'Đà Nẵng',
    description: 'Bánh dừa nướng thơm béo, giòn xốp — quà biếu đặc trưng của Đà Nẵng và miền Trung.',
    detail: 'Bánh dừa nướng Đà Nẵng là loại bánh khô, bảo quản được lâu, thường dùng làm quà biếu khi đi du lịch miền Trung. Bánh từ dừa nạo khô, bột mì, đường, trứng, nướng đến vàng giòn. Hương thơm đặc trưng của dừa nướng rất dễ nhận biết. Bánh nhỏ gọn, ăn kèm trà rất hợp.',
    ingredients: ['Dừa nạo khô', 'Bột mì', 'Đường', 'Trứng gà', 'Bơ', 'Vani'],
    occasion: 'Quà biếu, du lịch, hàng ngày',
    rating: 4.4,
    gradient: 'linear-gradient(135deg, #f5cba7 0%, #e59866 100%)',
    emoji: '🥥'
  }
];
